# -*- coding: utf-8 -*-
"""SetUp_Bot_Live.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sDeLi1WrnN4TOk7oyFv3Xy2GD4HKZBvR
"""

import requests

token = "TELEGRAM_BOT_TOKEN"
url = "https://trab-final-aa.onrender.com/mensagem"
dados = {"url": url}
resposta = requests.post(f"https://api.telegram.org/bot{token}/setWebhook", data=dados)
print(resposta.json())

